output_root: '../'
pytorch_data_dir: './datadrive/pytorch-data/'
experiment_name: "cityscapes"
res: 256
batch_size: 8
num_workers: 8
run_picie: True
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

model_paths:
  - "../checkpoints/cityscapes/cityscapes_exp1_date_Aug03_22-55-23/epoch=6-step=799.ckpt"
  # - "../saved_models/cocostuff27_vit_base_5.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
